# Generated by Django 5.1.5 on 2025-05-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_advertisement_post_advertisement'),
        ('posts', '0008_alter_post_slug'),
    ]

    operations = [
    ]
