# Generated by Django 5.1.5 on 2025-05-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_ban_reason_customuser_banned_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_email',
            field=models.BooleanField(default=False, verbose_name='Показывать мой email'),
        ),
    ]
