# Generated by Django 5.1.5 on 2025-05-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videopost', '0002_remove_videopost_preview_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
