# Generated by Django 5.1.5 on 2025-05-22 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videopost', '0003_alter_videopost_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='videopost.videocomment'),
        ),
    ]
