# Generated by Django 5.1.5 on 2025-05-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videopost', '0004_videocomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_videos/'),
        ),
    ]
