# docker-compose.yml

services:
  web:
    build: .
    container_name: web
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - nginx
    env_file:
      - .env
    environment:
      - DOCKERIZED=1        # <-- добавляем
    volumes:
      - ./static:/app/static
      - ./staticfiles:/app/staticfiles
      - media_volume:/media

  postojka:
    build:
      context: ./postojka
    container_name: postojka
    ports:
      - "8002:8000"
    restart: always
    depends_on:
      - db
    environment:
      - PG_NAME=chatty_db
      - PG_USER=chatty
      - PG_PASSWORD=chatty_db
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
    env_file:
      - .env

  nginx:
    build:
      context: ./nginx      # берёт nginx/Dockerfile и nginx.conf
    container_name: nginx
    depends_on:
      - web
    volumes:
      - media_volume:/media
    ports:
      - "80:80"

volumes:
  media_volume:

