# docker-compose.yml

services:
  web:
    build: .
    container_name: web
    environment:
      - DJANGO_SETTINGS_MODULE=chatty.settings.prod
      - DOCKERIZED=1
    command: gunicorn Chatty_green.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./static:/app/static
      - ./staticfiles:/app/staticfiles
      - media_volume:/media


#  postojka:
#    build:
#      context: ./postojka
#    container_name: postojka
#    ports:
#      - "8002:8000"
#    restart: always
   # depends_on:
#    environment:
#      - PG_NAME=chatty_db
#      - PG_USER=chatty
#      - PG_PASSWORD=chatty_db
#      - DB_HOST=host.docker.internal
#      - DB_PORT=5432
#    env_file:
#      - .env

  nginx:
    build:
      context: ./nginx      # берёт nginx/Dockerfile и nginx.conf
    container_name: nginx
    depends_on:
      - web
    volumes:
      - media_volume:/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"

volumes:
  media_volume:

