# Generated by Django 5.1.5 on 2025-06-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/images/', verbose_name='Изображение')),
                ('video', models.FileField(blank=True, null=True, upload_to='ads/videos/', verbose_name='Видеофайл')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Рекламное объявление',
                'verbose_name_plural': 'Рекламные объявления',
                'ordering': ['-created_at'],
            },
        ),
    ]
