# Generated by Django 5.1.5 on 2025-05-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='temp_field',
        ),
    ]
